apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-app
spec:
  resources:
    - name: appSource
      type: git
    - name: appImage
      type: image
  tasks:
    - name: build-tekton-app
      taskRef:
        name: build-app
      params:
        - name: contextDir
          value: .
      resources:
        inputs:
          - name: source
            resource: appSource
        outputs:
          - name: builtImage
            resource: appImage
    - name: deploy-kubernetes-service
      taskRef:
        name: openshift-client
      runAfter:
        - build-tekton-app
      resources:
        inputs:
          - name: source
            resource: appSource
      params:
        - name: ARGS
          value:
            - "apply"
            - "-f"
            - "/workspace/source/tekton/tekton-app-deployment.yaml"
            - "-f"
            - "/workspace/source/tekton/tekton-app-service.yaml"
