apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc2
spec:
  runPolicy: Serial

  source:
    type: Git
    git:
      uri: https://github.com/jonggyoukim/openshift-cicd-demo.git


  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:14-ubi7
        namespace: openshift
      env:
        - name: MYSQL_SERVICE_HOST
          value: demo-mysql

  output:
    to:
      kind: DockerImage
      name: 'jonggyoukim/bc2-app:last'
    pushSecret:
      name: dockerhub

  postCommit:
      script: "ls"

