apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc3
spec:
  runPolicy: Serial

  source:
    type: Git
    git:
      uri: https://github.com/jonggyoukim/openshift-cicd-demo.git


  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: MYSQL_SERVICE_HOST
          value: demo-mysql


  output:
    to:
      kind: DockerImage
      name: 'jonggyoukim/bc3-app:last'
    pushSecret:
      name: dockerhub


  postCommit:
      script: "ls"

