kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: bc4
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage('build') {
            openshift.withCluster() {
              openshift.selector("bc", "bc1").startBuild()
            }
          }
          stage('deploy') {
            openshift.withCluster() {
              openshift.selector("dc", "dc1").rollout().latest()
            }
          }
        }
