kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: build4
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('') {
          stage('build') {
            openshift.withCluster() {
              openshift.selector("bc", "build1-bc").startBuild()
            }
          }
          stage('deploy') {
            openshift.withCluster() {
              openshift.selector("dc", "dc-app").rollout().latest()
            }
          }
        }
