apiVersion: v1
kind: DeploymentConfig
metadata:
  name: dc-app
spec:
  replicas: 1
  selector:
    name: dc-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: dc-app
    spec:
      containers:
      - image: build1-app:latest
        name: build1-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MYSQL_SERVICE_HOST
          value: demo-mysql
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - build1-app
      from:
        kind: ImageStreamTag
        name: build1-app:latest
    type: ImageChange
