apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: shiftyou/demo-app
        env:
        - name: MYSQL_SERVICE_HOST
          value: demo-mysql
        ports:
        - containerPort: 8080
          name: demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: demo-app
