apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mysql
  labels:
    app: demo-mysql
spec:
  selector:
    matchLabels:
      app: demo-mysql

  template:
    metadata:
      labels:
        app: demo-mysql
    spec:
      containers:
      - name: demo-mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
